# Generated by Django 5.2.7 on 2025-10-15 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpoyeeDetailsModel',
            new_name='EmployeeDetailsModel',
        ),
    ]
