# Generated by Django 5.2.7 on 2025-10-15 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0004_alter_employeedetailsmodel_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendancedetailsmodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeattendancedetailsmodel',
            name='marked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeattendancedetailsmodel',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Half Day', 'Half Day')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedetailsmodel',
            name='job_profile',
            field=models.CharField(choices=[('technician', 'Technician')], max_length=200),
        ),
    ]
