# Generated by Django 5.2.7 on 2025-10-15 22:17

import django.db.models.deletion
import workJobApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerApp', '0001_initial'),
        ('employeeApp', '0005_alter_employeeattendancedetailsmodel_date_and_more'),
        ('shopApp', '0003_shopdetailsmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField(verbose_name='Reminder Date')),
                ('job_no', models.CharField(max_length=40, verbose_name='Job Number')),
                ('model', models.CharField(max_length=256, verbose_name='Model')),
                ('job_details', models.CharField(max_length=1000, verbose_name='Job Details')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress')], max_length=40, verbose_name='Status')),
                ('delivery', models.DateField(verbose_name='Delivery Date')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Customer Feedback')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost')),
                ('estimated_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimated Bill')),
                ('final_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Final Bill')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customerApp.customerdetailsmodel', verbose_name='Customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.shopdetailsmodel', verbose_name='Shop')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeApp.employeedetailsmodel', validators=[workJobApp.models.validate_technician])),
            ],
        ),
    ]
