# Generated by Django 5.2.7 on 2025-10-17 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0001_initial'),
        ('employeeApp', '0005_alter_employeeattendancedetailsmodel_date_and_more'),
        ('shopApp', '0003_shopdetailsmodel_name'),
        ('workJobApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdetailsmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Detail', 'verbose_name_plural': 'Job Details'},
        ),
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Actual Hours Worked'),
        ),
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Work Completed At'),
        ),
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Estimated Hours'),
        ),
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='first_time_fix',
            field=models.BooleanField(default=True, verbose_name='First Time Fix'),
        ),
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Labor Cost'),
        ),
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='parts_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Parts Cost'),
        ),
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='rework_required',
            field=models.BooleanField(default=False, verbose_name='Rework Required'),
        ),
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Work Started At'),
        ),
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tax Amount'),
        ),
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='jobdetailsmodel',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered')], max_length=40, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='jobdetailsmodel',
            index=models.Index(fields=['status', 'created_at'], name='workJobApp__status_e06473_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdetailsmodel',
            index=models.Index(fields=['technician', 'completed_at'], name='workJobApp__technic_17ef9c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdetailsmodel',
            index=models.Index(fields=['shop', 'delivery'], name='workJobApp__shop_id_1b0323_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdetailsmodel',
            index=models.Index(fields=['final_bill', 'completed_at'], name='workJobApp__final_b_5ada11_idx'),
        ),
    ]
