# Generated by Django 5.2.7 on 2026-09-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workJobApp', '0002_alter_jobdetailsmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetailsmodel',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('returned', 'Returned')], max_length=40, verbose_name='Status'),
        ),
    ]
