# Generated by Django 5.2.7 on 2026-09-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workJobApp', '0002_alter_jobdetailsmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='is_return',
            field=models.BooleanField(default=False, verbose_name='Is Return'),
        ),
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Returned At'),
        ),
    ]
