# Generated by Django 5.2.7 on 2026-09-06 20:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workJobApp', '0003_alter_jobdetailsmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='jobdetailsmodel',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20, verbose_name='Payment Status'),
        ),
    ]
