# Generated by Django 5.2.7 on 2025-10-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopdetailsmodel',
            old_name='user',
            new_name='owner',
        ),
    ]
