# Generated by Django 5.2.7 on 2025-10-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_rename_user_shopdetailsmodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='name',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
