# Generated by Django 5.2.7 on 2025-10-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpverificationmodel',
            old_name='opt_method',
            new_name='otp_method',
        ),
    ]
