# Generated by Django 5.2.7 on 2026-09-06 20:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentRecordApp', '0001_initial'),
        ('shopApp', '0003_shopdetailsmodel_name'),
        ('workJobApp', '0004_jobdetailsmodel_amount_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='workJobApp.jobdetailsmodel')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_allocations', to='paymentRecordApp.paymentrecorddetailsmodel')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.shopdetailsmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
