# Generated by Django 5.2.7 on 2025-10-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_rename_userdetails_userdetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsmodel',
            name='can_create_shops_count',
            field=models.IntegerField(default=0),
        ),
    ]
