name: Deploy to PythonAnywhere
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create and execute commands in console session
        run: |
          # Create a new console session
          CONSOLE_RESPONSE=$(curl -s -X POST \
            -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/consoles/")
          
          # Extract console ID
          CONSOLE_ID=$(echo $CONSOLE_RESPONSE | grep -o '"id":[0-9]*' | grep -o '[0-9]*')
          echo "Console ID: $CONSOLE_ID"
          
          # Function to send command to console
          send_command() {
            curl -X POST \
              -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d "{\"input\": \"$1\\n\"}" \
              "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/consoles/$CONSOLE_ID/send_input/"
            sleep 3  # Wait for command to execute
          }
          
          # Execute deployment commands
          send_command "cd /home/${{ secrets.PYTHONANYWHERE_USERNAME }}/mobile-crm-backend"
          send_command "git pull origin main"
          send_command "source ~/.virtualenvs/django-venv/bin/activate"
          send_command "pip install -r requirements.txt"
          send_command "python manage.py migrate"
          send_command "python manage.py collectstatic --noinput"
          
          # Kill the console
          curl -X DELETE \
            -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
            "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/consoles/$CONSOLE_ID/"
      
      - name: Reload webapp
        run: |
          curl -X POST \
            -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
            "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/webapps/${{ secrets.PYTHONANYWHERE_DOMAIN }}/reload/"
